/*
 * Copyright 2020 Sander Verdonschot.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.mangara.puzzles.gui;

import com.github.mangara.puzzles.data.Puzzle;

public class LogiquizPanel extends javax.swing.JPanel implements PuzzlePanel {

    /**
     * Creates new form LogiquizPanel
     */
    public LogiquizPanel() {
        initComponents();
    }

    @Override
    public void setPuzzle(Puzzle puzzle) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Puzzle getPuzzle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setMode(InteractionMode mode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cluesPanel = new javax.swing.JPanel();
        cluesLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        cluesLabel.setText("Clues:");

        javax.swing.GroupLayout cluesPanelLayout = new javax.swing.GroupLayout(cluesPanel);
        cluesPanel.setLayout(cluesPanelLayout);
        cluesPanelLayout.setHorizontalGroup(
            cluesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cluesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cluesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cluesPanelLayout.setVerticalGroup(
            cluesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cluesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cluesLabel)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        add(cluesPanel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cluesLabel;
    private javax.swing.JPanel cluesPanel;
    // End of variables declaration//GEN-END:variables

}
